version: '3'

services: 
    rabbitmq:
        image: rabbitmq:3.8.16-management
        container_name: "rabbitmq"
        hostname: host-rabbit        
        ports: 
            - "15672:15672"
            - "5672:5672"            
        volumes: 
           - ./data:/var/lib/rabbitmq
        environment: 
            - RABBITMQ_DEFAULT_VHOST=docker_vhost
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password